# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Minecraft
minecraft_version = 1.21.11
neoforge_version  = 21.11.42

supported_minecraft_versions = >=1.21.11
minecraft_version_range      = [1.21.11,)

# Mod Properties
project_name    = 1.21.11+neoforge
mod_version     = 2.9.0
mod_name        = Placeholder API NeoForge
mod_id          = placeholder-api-neoforge
mod_description = NeoForge port of Patbox's Text Placeholder API
mod_website     = https://modrinth.com/mod/placeholder-api-neoforge
mod_issues      = https://github.com/OffsetMods538/TextPlaceholderAPI-NeoForge/issues
mod_sources     = https://github.com/OffsetMods538/TextPlaceholderAPI-NeoForge
